// Real Data Seeds for Propel Platform
// Colleges, FRQs, Physics Simulations, Flashcard Decks

export const realColleges = [
  // Ivy League
  { name: 'Harvard University', sat: 1520, gpa: 4.0, accept_rate: 3 },
  { name: 'Yale University', sat: 1510, gpa: 4.0, accept_rate: 4 },
  { name: 'Princeton University', sat: 1520, gpa: 4.0, accept_rate: 3 },
  { name: 'Columbia University', sat: 1505, gpa: 4.0, accept_rate: 4 },
  { name: 'University of Pennsylvania', sat: 1510, gpa: 3.97, accept_rate: 5 },
  { name: 'Dartmouth College', sat: 1510, gpa: 3.99, accept_rate: 5 },
  { name: 'Brown University', sat: 1500, gpa: 3.97, accept_rate: 5 },
  { name: 'Cornell University', sat: 1485, gpa: 3.93, accept_rate: 7 },

  // Stanford, MIT, Duke, Northwestern
  { name: 'Stanford University', sat: 1505, gpa: 3.99, accept_rate: 4 },
  { name: 'MIT', sat: 1535, gpa: 4.0, accept_rate: 3 },
  { name: 'Duke University', sat: 1520, gpa: 4.0, accept_rate: 6 },
  { name: 'Northwestern University', sat: 1515, gpa: 4.0, accept_rate: 7 },

  // Top State Schools
  { name: 'UC Berkeley', sat: 1430, gpa: 3.92, accept_rate: 12 },
  { name: 'University of Michigan', sat: 1420, gpa: 3.90, accept_rate: 19 },
  { name: 'UCLA', sat: 1420, gpa: 3.90, accept_rate: 9 },
  { name: 'University of Virginia', sat: 1430, gpa: 3.95, accept_rate: 15 },
  { name: 'University of Texas at Austin', sat: 1360, gpa: 3.84, accept_rate: 25 },

  // Liberal Arts & Top 25
  { name: 'Williams College', sat: 1500, gpa: 3.98, accept_rate: 7 },
  { name: 'Amherst College', sat: 1495, gpa: 3.97, accept_rate: 8 },
  { name: 'Swarthmore College', sat: 1490, gpa: 3.96, accept_rate: 7 },
  { name: 'Bowdoin College', sat: 1485, gpa: 3.95, accept_rate: 8 },
  { name: 'Middlebury College', sat: 1480, gpa: 3.94, accept_rate: 10 },
  { name: 'Vanderbilt University', sat: 1500, gpa: 3.92, accept_rate: 9 },
  { name: 'Rice University', sat: 1520, gpa: 3.95, accept_rate: 9 },
  { name: 'Carnegie Mellon University', sat: 1520, gpa: 3.93, accept_rate: 9 },
  { name: 'University of Chicago', sat: 1520, gpa: 3.95, accept_rate: 6 },
  { name: 'Johns Hopkins University', sat: 1490, gpa: 3.92, accept_rate: 7 },
  { name: 'Washington University in St. Louis', sat: 1495, gpa: 3.92, accept_rate: 12 },
];

export const realFRQs = [
  // Physics 1 FRQs
  {
    subject: 'Physics 1',
    title: 'Projectile Motion Analysis',
    question: 'A projectile is launched from ground level at an angle of 45° with an initial velocity of 20 m/s. (a) Find the maximum height reached. (b) Find the range of the projectile. (c) Find the time of flight.',
    solution: 'Using v₀ = 20 m/s, θ = 45°:\n(a) Max height: h = (v₀²sin²θ)/(2g) = (400×0.5)/(20) = 10 m\n(b) Range: R = (v₀²sin2θ)/g = (400×1)/10 = 40 m\n(c) Time: t = (2v₀sinθ)/g = (2×20×0.707)/10 = 2.83 s',
    hints: ['Use the kinematic equations for projectile motion', 'Remember that sin(45°) = √2/2', 'The maximum height occurs when vertical velocity = 0'],
    difficulty: 'medium',
  },
  {
    subject: 'Physics 1',
    title: 'Newton\'s Second Law and Friction',
    question: 'A 5 kg block is pushed across a horizontal surface with an applied force of 25 N. The coefficient of kinetic friction is 0.3. (a) Calculate the friction force. (b) Calculate the net force on the block. (c) Calculate the acceleration.',
    solution: 'Given: m = 5 kg, F_applied = 25 N, μ_k = 0.3\n(a) f_k = μ_k × N = 0.3 × 50 = 15 N\n(b) F_net = F_applied - f_k = 25 - 15 = 10 N\n(c) a = F_net/m = 10/5 = 2 m/s²',
    hints: ['First calculate the normal force (weight)', 'Remember that friction opposes motion', 'Use F = ma to find acceleration'],
    difficulty: 'easy',
  },
  {
    subject: 'Physics 1',
    title: 'Energy Conservation and Simple Harmonic Motion',
    question: 'A mass of 2 kg attached to a spring with k = 100 N/m is displaced 0.1 m and released. (a) Find the maximum potential energy. (b) Find the maximum kinetic energy. (c) Find the maximum velocity.',
    solution: 'Given: m = 2 kg, k = 100 N/m, x_max = 0.1 m\n(a) U_max = ½kx² = ½(100)(0.01) = 0.5 J\n(b) KE_max = U_max = 0.5 J (energy conservation)\n(c) v_max = √(2KE/m) = √(1/2) = 0.707 m/s',
    hints: ['Use PE = ½kx² for spring potential energy', 'By energy conservation, max KE = max PE', 'Use KE = ½mv² to find velocity'],
    difficulty: 'medium',
  },
  {
    subject: 'Physics 1',
    title: 'Circular Motion and Centripetal Force',
    question: 'A 1500 kg car takes a circular turn with radius 50 m at a speed of 15 m/s. (a) Calculate the centripetal acceleration. (b) Calculate the centripetal force. (c) Find the minimum coefficient of friction needed.',
    solution: 'Given: m = 1500 kg, r = 50 m, v = 15 m/s\n(a) a_c = v²/r = 225/50 = 4.5 m/s²\n(b) F_c = ma_c = 1500 × 4.5 = 6750 N\n(c) μ_min = a_c/g = 4.5/10 = 0.45',
    hints: ['Centripetal acceleration points toward the center', 'Use F_c = mv²/r for centripetal force', 'Friction provides the centripetal force'],
    difficulty: 'medium',
  },
  {
    subject: 'Physics 1',
    title: 'Impulse and Momentum',
    question: 'A 0.5 kg ball moving at 10 m/s collides with a wall and rebounds at 8 m/s in the opposite direction. If the collision lasts 0.1 s: (a) Find the change in momentum. (b) Calculate the impulse. (c) Find the average force during collision.',
    solution: 'Given: m = 0.5 kg, v_i = 10 m/s, v_f = -8 m/s, Δt = 0.1 s\n(a) Δp = m(v_f - v_i) = 0.5(-8-10) = -9 kg·m/s\n(b) J = Δp = -9 N·s\n(c) F_avg = J/Δt = -9/0.1 = -90 N',
    hints: ['Remember direction matters in momentum', 'Impulse = force × time = change in momentum', 'Use J = F_avg × Δt'],
    difficulty: 'medium',
  },
  {
    subject: 'Physics 1',
    title: 'Work and Power',
    question: 'A 2 kg object is lifted vertically 5 m against gravity. (a) Calculate the work done against gravity. (b) If this is done in 10 seconds, what is the average power? (c) What is the instantaneous power if the object is lifted with constant velocity?',
    solution: 'Given: m = 2 kg, h = 5 m, t = 10 s, g = 10 m/s²\n(a) W = mgh = 2 × 10 × 5 = 100 J\n(b) P_avg = W/t = 100/10 = 10 W\n(c) v = h/t = 0.5 m/s; F = mg = 20 N; P = Fv = 20 × 0.5 = 10 W',
    hints: ['Work against gravity = mgh', 'Power = Work/time', 'For constant velocity, power = force × velocity'],
    difficulty: 'easy',
  },
  {
    subject: 'Physics 1',
    title: 'Elastic and Inelastic Collisions',
    question: 'Two blocks collide on a frictionless surface: Block A (mass 2 kg, v = 6 m/s) hits Block B (mass 4 kg, at rest). If the collision is perfectly inelastic: (a) Find the final velocity. (b) Calculate kinetic energy before collision. (c) Calculate kinetic energy after collision.',
    solution: 'Given: m_A = 2 kg, v_A = 6 m/s, m_B = 4 kg, v_B = 0\n(a) By momentum conservation: (2)(6) = (2+4)v_f → v_f = 2 m/s\n(b) KE_i = ½(2)(36) + 0 = 36 J\n(c) KE_f = ½(6)(4) = 12 J\nEnergy lost = 24 J (due to inelastic collision)',
    hints: ['Momentum is always conserved', 'In inelastic collisions, kinetic energy is lost', 'Perfectly inelastic means objects stick together'],
    difficulty: 'hard',
  },
  {
    subject: 'Physics 1',
    title: 'Gravitation and Orbital Motion',
    question: 'The Moon orbits Earth at an average distance of 3.84 × 10⁸ m. If Earth\'s mass is 5.97 × 10²⁴ kg, find: (a) The gravitational force on the Moon. (b) The orbital velocity of the Moon. (c) The orbital period in days.',
    solution: 'Given: r = 3.84 × 10⁸ m, M_E = 5.97 × 10²⁴ kg, m_moon = 7.35 × 10²² kg, G = 6.67 × 10⁻¹¹\n(a) F = GMm/r² = (6.67 × 10⁻¹¹)(5.97 × 10²⁴)(7.35 × 10²²)/(3.84 × 10⁸)² ≈ 1.98 × 10²⁰ N\n(b) v = √(GM/r) = √((6.67 × 10⁻¹¹ × 5.97 × 10²⁴)/(3.84 × 10⁸)) ≈ 1020 m/s\n(c) T = 2πr/v ≈ 2.37 × 10⁶ seconds ≈ 27.4 days',
    hints: ['Use Newton\'s law of gravitation for force', 'Orbital velocity: v = √(GM/r)', 'Period: T = 2πr/v'],
    difficulty: 'hard',
  },
  {
    subject: 'Physics 1',
    title: 'Waves and Sound',
    question: 'A sound wave has a frequency of 440 Hz and travels through air at 343 m/s. (a) Find the wavelength. (b) If the sound intensity is 1 × 10⁻⁶ W/m², what is the sound level in decibels? (c) What frequency would an observer moving toward the source at 10 m/s hear?',
    solution: 'Given: f = 440 Hz, v = 343 m/s, I = 1 × 10⁻⁶ W/m², v_observer = 10 m/s\n(a) λ = v/f = 343/440 = 0.78 m\n(b) dB = 10log(I/I₀) = 10log(10⁻⁶/10⁻¹²) = 10log(10⁶) = 60 dB\n(c) f\' = f(v+v_observer)/v = 440(343+10)/343 ≈ 454 Hz (Doppler effect)',
    hints: ['Wavelength = velocity/frequency', 'Sound level in dB uses logarithmic scale', 'Doppler effect: f\' = f(v±v_observer)/v'],
    difficulty: 'hard',
  },
  {
    subject: 'Physics 1',
    title: 'Rotational Motion and Torque',
    question: 'A uniform rod of mass 2 kg and length 1 m rotates about one end. (a) Calculate the moment of inertia. (b) If a 10 N force is applied perpendicular to the rod at the other end, find the torque. (c) Calculate the angular acceleration.',
    solution: 'Given: m = 2 kg, L = 1 m, F = 10 N\n(a) I = (1/3)mL² = (1/3)(2)(1) = 0.67 kg·m²\n(b) τ = F × L = 10 × 1 = 10 N·m\n(c) α = τ/I = 10/0.67 = 15 rad/s²',
    hints: ['For rod about end: I = (1/3)mL²', 'Torque = force × perpendicular distance', 'Use τ = Iα (rotational analog of F = ma)'],
    difficulty: 'medium',
  },

  // Chemistry FRQs (simplified set)
  {
    subject: 'Chemistry',
    title: 'Stoichiometry: Limiting Reactant',
    question: 'In the reaction 2H₂ + O₂ → 2H₂O, if 8 grams of H₂ reacts with 32 grams of O₂: (a) Identify the limiting reactant. (b) Calculate moles of water produced. (c) Calculate grams of excess reactant remaining.',
    solution: 'Molar masses: H₂ = 2, O₂ = 32, H₂O = 18\nMoles: H₂ = 8/2 = 4 mol, O₂ = 32/32 = 1 mol\n(a) O₂ is limiting (needs 2 mol H₂ per 1 mol O₂; we only have 4 mol H₂)\n(b) Water produced = 1 mol O₂ × 2 mol H₂O = 2 mol H₂O = 36 g\n(c) H₂ used = 2 mol, H₂ remaining = 2 mol = 4 g excess',
    hints: ['Convert to moles using molar mass', 'Compare mole ratios from balanced equation', 'Limiting reactant is completely consumed'],
    difficulty: 'medium',
  },
  {
    subject: 'Chemistry',
    title: 'Equilibrium and Le Chatelier\'s Principle',
    question: 'For the reaction: 2NO₂ ⇌ N₂O₄, K_c = 10 at 25°C. If 0.1 M NO₂ is allowed to reach equilibrium: (a) Write the ICE table. (b) Calculate equilibrium concentrations. (c) Explain how adding N₂O₄ shifts equilibrium.',
    solution: 'ICE table:\n       2NO₂ ⇌ N₂O₄\nI: 0.1    0\nC: -2x   +x\nE: 0.1-2x x\n\n(b) K_c = [N₂O₄]/[NO₂]² = x/(0.1-2x)² = 10\nSolving: x ≈ 0.067 M\n[NO₂] = 0.034 M, [N₂O₄] = 0.067 M\n(c) Adding N₂O₄ shifts equilibrium left (toward reactants)',
    hints: ['Use ICE tables for equilibrium problems', 'Substitute into equilibrium expression', 'Le Chatelier: system shifts to counteract stress'],
    difficulty: 'hard',
  },
  {
    subject: 'Chemistry',
    title: 'Acids, Bases, and pH',
    question: 'A 0.1 M HCl solution: (a) Calculate the pH. (b) Calculate the pOH. (c) Calculate the [OH⁻].',
    solution: '[H⁺] = 0.1 M = 10⁻¹ M\n(a) pH = -log[H⁺] = -log(0.1) = 1\n(b) pOH = 14 - pH = 14 - 1 = 13\n(c) [OH⁻] = 10⁻pOH = 10⁻¹³ = 1 × 10⁻¹³ M',
    hints: ['pH = -log[H⁺]', 'pH + pOH = 14', '[H⁺][OH⁻] = 1 × 10⁻¹⁴'],
    difficulty: 'easy',
  },
  {
    subject: 'Chemistry',
    title: 'Redox Reactions and Balancing',
    question: 'Balance the following redox reaction in acidic solution: MnO₄⁻ + Fe²⁺ → Mn²⁺ + Fe³⁺',
    solution: 'Step 1: Write half-reactions\nReduction: MnO₄⁻ + 8H⁺ + 5e⁻ → Mn²⁺ + 4H₂O\nOxidation: Fe²⁺ → Fe³⁺ + e⁻\n\nStep 2: Balance electrons (×5)\n5Fe²⁺ → 5Fe³⁺ + 5e⁻\n\nStep 3: Overall\nMnO₄⁻ + 5Fe²⁺ + 8H⁺ → Mn²⁺ + 5Fe³⁺ + 4H₂O',
    hints: ['Identify oxidation states', 'Separate oxidation and reduction', 'Balance charge with H⁺ or OH⁻'],
    difficulty: 'hard',
  },
  {
    subject: 'Chemistry',
    title: 'Thermodynamics and Enthalpy',
    question: 'For the reaction: C + O₂ → CO₂, ΔH°_rxn = -393 kJ. How much heat is released when 12 g of carbon burns?',
    solution: 'Molar mass of C = 12 g/mol\nMoles of C = 12g / 12 g/mol = 1 mol\n\nSince ΔH°_rxn = -393 kJ per mole of C burned,\nHeat released = 1 mol × (-393 kJ/mol) = -393 kJ\n\nTherefore, 393 kJ of heat is released (exothermic)',
    hints: ['Convert grams to moles', 'Match stoichiometry with given ΔH', 'Negative ΔH means exothermic (heat released)'],
    difficulty: 'easy',
  },
  {
    subject: 'Chemistry',
    title: 'Orbital Theory and Quantum Numbers',
    question: 'For an electron in a hydrogen atom with n=3, l=2: (a) Name the orbital type. (b) What are the possible ml values? (c) Draw the orbital shape.',
    solution: '(a) n=3, l=2 is a 3d orbital\n(b) For l=2, ml = -2, -1, 0, +1, +2 (5 orbitals)\n(c) d orbitals have cloverleaf shape with 4 lobes (dxy type shows two lobes oriented along x and y axes)',
    hints: ['l value: 0=s, 1=p, 2=d, 3=f', 'ml ranges from -l to +l', 'd orbitals are complex but have characteristic cloverleaf pattern'],
    difficulty: 'medium',
  },
  {
    subject: 'Chemistry',
    title: 'Molecular Geometry and VSEPR',
    question: 'Determine the molecular geometry for: (a) CO₂, (b) H₂O, (c) NH₃ using VSEPR theory.',
    solution: '(a) CO₂: 2 bonding pairs, 0 lone pairs → Linear\n(b) H₂O: 2 bonding pairs, 2 lone pairs → Bent/Angular\n(c) NH₃: 3 bonding pairs, 1 lone pair → Trigonal pyramidal',
    hints: ['Count total electron pairs (bonding + lone)', 'Electron geometry vs molecular geometry', 'Lone pairs repel more than bonding pairs'],
    difficulty: 'easy',
  },
  {
    subject: 'Chemistry',
    title: 'Kinetics and Reaction Rates',
    question: 'For the reaction A → products, the rate law is rate = k[A]². If [A] is doubled, by what factor does the reaction rate increase?',
    solution: 'Rate law: rate = k[A]²\n\nIf [A]_new = 2[A]_original:\nrate_new = k(2[A])² = k(4[A]²) = 4k[A]²\n\nrate_new / rate_original = 4k[A]² / k[A]² = 4\n\nThe reaction rate increases by a factor of 4.',
    hints: ['Substitute new concentration into rate law', 'Compare new rate to original rate', 'Order of reaction determines how concentration affects rate'],
    difficulty: 'medium',
  },

  // Biology FRQs
  {
    subject: 'Biology',
    title: 'Cellular Respiration: Glycolysis',
    question: 'Describe the process of glycolysis. Include: (a) Location in the cell, (b) Inputs and outputs, (c) Net ATP and NADH produced.',
    solution: '(a) Glycolysis occurs in the cytoplasm\n(b) Input: 1 glucose (6C), 2 ATP, 2 NAD⁺\n    Output: 2 pyruvate (3C each), 4 ATP, 2 NADH\n(c) Net yield: 2 ATP (gained 4, used 2) and 2 NADH\n\nKey step: Glucose → Glucose-6-phosphate → ... → 2 Pyruvate',
    hints: ['10 steps in glycolysis', 'Investment phase uses 2 ATP', 'Payoff phase produces 4 ATP'],
    difficulty: 'medium',
  },
  {
    subject: 'Biology',
    title: 'Photosynthesis: Light and Dark Reactions',
    question: 'Compare light reactions and dark reactions (Calvin cycle): (a) Where do they occur? (b) What are inputs/outputs? (c) How are they connected?',
    solution: '(a) Light reactions: thylakoid membrane; Dark reactions: stroma\n(b) Light: Input H₂O + light → Output O₂, ATP, NADPH\n    Dark: Input CO₂ + ATP + NADPH → Output G3P, glucose\n(c) ATP and NADPH from light reactions power the Calvin cycle',
    hints: ['Light reactions produce energy carriers', 'Dark reactions (Calvin cycle) use energy to fix CO₂', 'They are interdependent'],
    difficulty: 'hard',
  },
  {
    subject: 'Biology',
    title: 'Genetics: Mendelian Inheritance',
    question: 'A pea plant with tall height (T) and green seeds (G) is crossed with a short plant (t) with yellow seeds (g). Assuming independent assortment: (a) What are the gametes? (b) What is the genotypic ratio? (c) What fraction are tall with yellow seeds?',
    solution: 'Parent 1: TtGg → gametes: TG, Tg, tG, tg\nParent 2: ttgg → gametes: tg\n\n(a) 4 types of gametes from heterozygous parent\n(b) 4 genotypes in 1:1:1:1 ratio\n(c) Tall with yellow: TtGg = 0 (no Tt with gg possible)\n    Actually: ttGg = 1/4 (short with yellow)',
    hints: ['Draw Punnett square (4×1)', 'Tt = tall, tt = short (assuming T is dominant)', 'Use dihybrid cross rules'],
    difficulty: 'medium',
  },
  {
    subject: 'Biology',
    title: 'DNA Replication and Protein Synthesis',
    question: 'Explain the central dogma of molecular biology: (a) How is DNA replicated? (b) How is mRNA created from DNA? (c) How is mRNA translated into protein?',
    solution: '(a) DNA replication: DNA → DNA (semiconservative, both strands serve as templates)\n(b) Transcription: DNA → mRNA (RNA polymerase reads coding strand, creates mRNA)\n(c) Translation: mRNA → Protein (ribosome reads codons, tRNA brings amino acids)',
    hints: ['DNA replication: 5→3 direction', 'Transcription produces mRNA (U not T)', 'Translation uses genetic code to build proteins'],
    difficulty: 'hard',
  },
  {
    subject: 'Biology',
    title: 'Ecology: Energy Flow and Food Chains',
    question: 'In a food chain: Grass → Grasshopper → Bird → Hawk, if grass contains 100,000 kilocalories: (a) How much energy reaches the hawk? (b) Why is there energy loss at each level? (c) What is the trophic efficiency?',
    solution: '(a) Using 10% efficiency rule:\n    Grass: 100,000 kcal\n    Grasshopper: 10,000 kcal (10%)\n    Bird: 1,000 kcal (10%)\n    Hawk: 100 kcal (10%)\n\n(b) Energy lost as heat, cellular respiration, waste\n(c) Trophic efficiency = 10% (typical for ecosystems)',
    hints: ['Most energy is lost as heat', '~90% lost at each trophic level', 'Explains why ecosystems support few top predators'],
    difficulty: 'easy',
  },
  {
    subject: 'Biology',
    title: 'Evolution and Natural Selection',
    question: 'Explain Darwin\'s theory of natural selection using the peppered moth example: (a) What changed in the population? (b) Why did the change occur? (c) What does this illustrate about evolution?',
    solution: '(a) Before: mostly light moths; After (industrial revolution): mostly dark moths\n(b) Natural selection: dark moths better camouflaged on soot-covered trees, survived predation\n(c) Illustrates: Evolution by natural selection; traits providing advantage increase in population; evolution can occur quickly',
    hints: ['Environmental change → selective pressure', 'Individuals best adapted survive and reproduce', 'This is microevolution (within species change)'],
    difficulty: 'medium',
  },
  {
    subject: 'Biology',
    title: 'Human Body Systems: Homeostasis',
    question: 'Describe how the body maintains homeostasis for blood glucose: (a) What gland and hormones are involved? (b) When glucose is too high, what happens? (c) When glucose is too low, what happens?',
    solution: '(a) Pancreas produces insulin and glucagon\n(b) High glucose: Pancreas releases insulin → increases glucose uptake by cells → blood glucose decreases\n(c) Low glucose: Pancreas releases glucagon → increases glucose release from liver → blood glucose increases\n\nThis negative feedback maintains ~90-100 mg/dL',
    hints: ['Insulin lowers blood glucose', 'Glucagon raises blood glucose', 'This is a negative feedback loop'],
    difficulty: 'medium',
  },

  // US History FRQs
  {
    subject: 'US History',
    title: 'Causes of the American Revolution',
    question: 'Analyze three causes that led to the American Revolution. For each, explain the action and colonial response.',
    solution: 'Three major causes:\n1. Taxation without representation (Stamp Act 1765): Britain imposed taxes without colonial consent → colonists protested "No taxation without representation"\n2. Quartering Act: Required colonists to house British soldiers → colonial resentment\n3. Intolerable Acts (1774): Punished Boston Tea Party → united colonies in opposition\n\nThese accumulated grievances led to military conflict in 1775.',
    hints: ['Consider economic, political, and social grievances', 'Timeline: 1765-1775 escalation', 'Enlightenment ideas influenced colonial philosophy'],
    difficulty: 'hard',
  },
  {
    subject: 'US History',
    title: 'Civil War Causes and Consequences',
    question: 'Identify three causes of the Civil War and analyze how each divided the nation.',
    solution: 'Three main causes:\n1. Slavery expansion: Southern support for slavery in new territories vs. Northern opposition → Dred Scott decision, Kansas-Nebraska Act intensified conflict\n2. State\'s rights: South argued states could nullify federal laws; North rejected this doctrine\n3. Election of Lincoln (1860): South feared Republican anti-slavery stance → secession\n\nConsequences: 620,000 deaths, ended slavery, Reconstruction period, strengthened federal authority',
    hints: ['North = free labor; South = plantation economy', 'Constitutional vs. political disagreements', '1860-1865 conflict'],
    difficulty: 'hard',
  },
  {
    subject: 'US History',
    title: 'Westward Expansion and Native Americans',
    question: 'Describe the impact of westward expansion (1800-1890) on Native Americans.',
    solution: 'Impact:\n1. Treaty violations: Fort Laramie, Fort Sumter treaties broken\n2. Forced relocations: Indian Removal Act (1830), Trail of Tears\n3. Reservation system: Confined tribes to small areas\n4. Buffalo extinction: Destroyed Native American food source\n5. Assimilation policies: Boarding schools, bans on native languages\n6. Population decimated: Disease, warfare, starvation\n\nNet effect: Near complete loss of Native American sovereignty and culture',
    hints: ['Manifest Destiny justified westward movement', 'Homestead Act (1862) accelerated settlement', 'Sand Creek Massacre and Wounded Knee were key conflicts'],
    difficulty: 'hard',
  },
  {
    subject: 'US History',
    title: 'Progressive Era Reforms (1890-1920)',
    question: 'Identify and explain three major Progressive Era reforms and their impact.',
    solution: 'Three reforms:\n1. Antitrust laws: Sherman Antitrust Act (1890) broke up monopolies → Standard Oil case\n2. Food safety: Upton Sinclair\'s "The Jungle" → Pure Food and Drug Act (1906)\n3. Labor regulations: Child labor laws, 8-hour workday, worker safety standards\n4. Political reforms: 17th Amendment (direct election of senators), women\'s suffrage (19th Amendment)\n\nImpact: Reduced corporate power, improved working conditions, expanded voting rights',
    hints: ['Roosevelt as progressive reformer', 'Muckraking journalists exposed problems', 'Federal government became more interventionist'],
    difficulty: 'medium',
  },
  {
    subject: 'US History',
    title: 'Great Depression and New Deal',
    question: 'Explain the causes of the Great Depression and evaluate the effectiveness of FDR\'s New Deal programs.',
    solution: 'Causes:\n1. Stock market speculation and crash (1929)\n2. Bank failures (no FDIC insurance)\n3. Reduced consumer spending\n4. International debt issues (war reparations)\n5. Agricultural crisis (Dust Bowl)\n\nNew Deal programs (1933-1939):\n- Relief (CCC, WPA): Immediate aid to unemployed\n- Recovery (NRA, AAA): Economic stimulus\n- Reform (Social Security, FDIC): Long-term stability\n\nEffectiveness: Debated - reduced unemployment but didn\'t fully end depression; WWII had greater impact',
    hints: ['Black Tuesday = Oct 29, 1929', 'Hoovervilles showed desperation', 'New Deal lasted 6 years'],
    difficulty: 'hard',
  },
];

export const realSimulations = [
  {
    name: 'Projectile Motion',
    subject: 'Physics',
    topic: 'Mechanics',
    description: 'Interactive simulation of projectile motion with adjustable launch angle and initial velocity',
    config: {
      g: 9.8,
      initialVelocity: 20,
      angle: 45,
      mass: 1,
      friction: 0,
    },
  },
  {
    name: 'Spring Mass System',
    subject: 'Physics',
    topic: 'Oscillations',
    description: '3D visualization of a mass oscillating on a spring with variable spring constant and damping',
    config: {
      k: 50,
      mass: 1,
      damping: 0.1,
      initialDisplacement: 0.1,
    },
  },
  {
    name: 'Circular Motion',
    subject: 'Physics',
    topic: 'Mechanics',
    description: 'Object moving in a circle with adjustable radius and velocity showing centripetal force',
    config: {
      radius: 5,
      mass: 1,
      velocity: 5,
      friction: 0,
    },
  },
  {
    name: 'Pendulum Motion',
    subject: 'Physics',
    topic: 'Oscillations',
    description: 'Simple pendulum showing period and frequency with variable length and amplitude',
    config: {
      length: 1,
      mass: 1,
      damping: 0.05,
      initialAngle: 0.3,
    },
  },
  {
    name: 'Elastic Collisions',
    subject: 'Physics',
    topic: 'Mechanics',
    description: '1D collision simulator showing conservation of momentum and energy',
    config: {
      mass1: 2,
      mass2: 1,
      velocity1: 5,
      velocity2: 0,
    },
  },
];

export const realFlashcardDecks = [
  {
    name: 'SAT Vocabulary',
    subject: 'Standardized Testing',
    cards: [
      { front: 'Ubiquitous', back: 'Present, found, or done everywhere; constantly encountered' },
      { front: 'Ephemeral', back: 'Lasting for a very short time; fleeting' },
      { front: 'Perspicacious', back: 'Having keen insight, judgment, or understanding' },
      { front: 'Serendipity', back: 'Finding good things by chance; happy coincidence' },
      { front: 'Meticulous', back: 'Very careful and precise; showing great attention to detail' },
      { front: 'Sanguine', back: 'Optimistic and confident about the future' },
      { front: 'Obfuscate', back: 'To deliberately make something unclear or difficult to understand' },
      { front: 'Equanimity', back: 'Mental calmness, composure, and evenness of temper' },
      { front: 'Amalgamate', back: 'To combine or join together; to form a whole' },
      { front: 'Vicissitude', back: 'A change of circumstances or fortune; ups and downs' },
    ],
  },
  {
    name: 'AP Biology Concepts',
    subject: 'Biology',
    cards: [
      { front: 'Homeostasis', back: 'Maintenance of stable internal conditions despite external changes' },
      { front: 'Photosynthesis', back: 'Process converting light energy to chemical energy in glucose' },
      { front: 'DNA Replication', back: 'Process creating exact copies of DNA for cell division' },
      { front: 'Mitosis', back: 'Cell division producing two identical diploid daughter cells' },
      { front: 'Meiosis', back: 'Cell division producing four haploid sex cells (gametes)' },
      { front: 'Natural Selection', back: 'Mechanism of evolution where favorable traits become more common' },
      { front: 'Enzyme', back: 'Protein that catalyzes (speeds up) biochemical reactions' },
      { front: 'ATP', back: 'Adenosine triphosphate; primary energy currency of cells' },
      { front: 'Osmosis', back: 'Movement of water across semipermeable membrane from high to low solute' },
      { front: 'Mutation', back: 'Change in DNA sequence that can affect organism phenotype' },
    ],
  },
  {
    name: 'AP Chemistry Formulas',
    subject: 'Chemistry',
    cards: [
      { front: 'Molarity', back: 'M = mol solute / L solution' },
      { front: 'pH', back: 'pH = -log[H⁺]' },
      { front: 'pOH', back: 'pOH = -log[OH⁻]' },
      { front: 'pH + pOH', back: '= 14 (at 25°C)' },
      { front: 'Henderson-Hasselbalch', back: 'pH = pKa + log([A⁻]/[HA])' },
      { front: 'Q (reaction quotient)', back: 'Q = [products]/[reactants] (same form as K, but not at equilibrium)' },
      { front: 'Ka (acid dissociation)', back: 'Ka = [H⁺][A⁻]/[HA]' },
      { front: 'Kb (base dissociation)', back: 'Kb = [BH⁺][OH⁻]/[B]' },
      { front: 'Kw (water dissociation)', back: 'Kw = [H⁺][OH⁻] = 1.0 × 10⁻¹⁴' },
      { front: 'Gas Law', back: 'PV = nRT (P=pressure, V=volume, n=moles, R=8.314, T=kelvin)' },
    ],
  },
  {
    name: 'US History Timeline',
    subject: 'US History',
    cards: [
      { front: '1776', back: 'Declaration of Independence signed; American Revolution underway' },
      { front: '1783', back: 'Treaty of Paris ends American Revolution; US independence recognized' },
      { front: '1787', back: 'Constitutional Convention; U.S. Constitution drafted' },
      { front: '1803', back: 'Louisiana Purchase doubles size of the United States' },
      { front: '1861-1865', back: 'American Civil War: Union vs. Confederacy' },
      { front: '1865', back: '13th Amendment abolishes slavery' },
      { front: '1920', back: '19th Amendment grants women voting rights' },
      { front: '1929', back: 'Stock market crash; Great Depression begins' },
      { front: '1941', back: 'Pearl Harbor attack; US enters World War II' },
      { front: '1963', back: 'March on Washington; MLK "I Have a Dream" speech' },
    ],
  },
  {
    name: 'Global Politics & Economics',
    subject: 'World Cultures',
    cards: [
      { front: 'GDP', back: 'Gross Domestic Product; total economic output of a country' },
      { front: 'Inflation', back: 'Increase in price of goods; decrease in purchasing power' },
      { front: 'Monopoly', back: 'Market dominated by single seller with no competition' },
      { front: 'Supply & Demand', back: 'Supply: quantity available; Demand: quantity wanted at price' },
      { front: 'Socialism', back: 'Economic system where means of production are collectively owned' },
      { front: 'Democracy', back: 'System where power rests with people through voting/representation' },
      { front: 'Authoritarianism', back: 'System with strong leader/government, limited individual freedoms' },
      { front: 'UN (United Nations)', back: 'International organization promoting peace, security, cooperation' },
      { front: 'NATO', back: 'North Atlantic Treaty Organization; military alliance of 32 countries' },
      { front: 'Globalization', back: 'Worldwide integration of trade, communication, and culture' },
    ],
  },
];
